import tkinter
import datetime

from datetime import datetime
from tkinter import *
import tkinter as tk
from tkinter import ttk
from tkinter import messagebox as mb
from PIL import Image, ImageTk

availableslots = ['10', '11', '12', '13', '14', '15', '16', '19', '20', '21', '22', '23', '24', '25', '28', '29', '30', '31', '32', '33', '34', '37', '38', '39', '40', '41', '42', '43']

def generate():
    partyidget = partyid.get()
    slotget = slot.get()
    nameget = name.get()
    typeget = type.get()
    hdbidget = hdbid.get()
    costget = cost.get()

    slotrow = f"      '{slotget}':"
    displayrow = f"        displayed: PLAYER_HEAD 1 name:&c{nameget} lore:&7Тип:&d_{typeget}|&7HDB-ID:&d_{hdbidget}|&7Цена:&d_%price%_Токенов"
    costrow = f'        cost: {costget}'
    messagerow = "        message: &bТокены &8» &7Спасибо за покупку, %player%! &c-%price% токенов."
    commandsrow1 = '        commands:'
    commandsrow2 = f"        - 'hdb give {hdbidget} 1 %player%'"

    reshetka = '#'
    date = datetime.today()
    datestr = str(date)
    if slotget in availableslots:
        print(reshetka, "Automatically generated", date, "through the MrUDD program - https://github.com/MrUDDoff/GeneratorTokenShop")
        print(slotrow)
        print(displayrow)
        print(costrow)
        print(messagerow)
        print(commandsrow1)
        print(commandsrow2)
        with open(f"autogenerated{partyidget}.yml", "a", encoding="utf-8") as file:
            file.write('\n' + reshetka + reshetka + reshetka + "Automatically generated" + " " + datestr + " " "through the MrUDD program - https://github.com/MrUDDoff/GeneratorTokenShop" + '\n' + slotrow + '\n' + displayrow + '\n' + costrow + '\n' + messagerow + '\n' + commandsrow1 + '\n' + commandsrow2)
        mb.showinfo(
        "Инфо", 
        "Предмет создан!")
    else:
        mb.showerror(
        "Ошибка", 
        "Запрещённый слот!")

root = Tk()

root.title("Generator Token Shop (Head's edition)")
root.geometry("550x550")

#frames
partyidframe = LabelFrame(root, text="PartyID")
slotframe = LabelFrame(root, text="Slot ID")
nameframe = LabelFrame(root, text="Name")
typeframe = LabelFrame(root, text="Type")
hdbidframe = LabelFrame(root, text="HDBID")
costframe = LabelFrame(root, text="Cost")


#Entrys
partyid = Entry(partyidframe, width=60, justify=CENTER)
slot = Entry(slotframe, width=60, justify=CENTER)
name = Entry(nameframe, width=60, justify=CENTER)
loretype = Entry(typeframe, width=60, justify=CENTER)
hdbid = Entry(hdbidframe, width=60, justify=CENTER)
cost = Entry(costframe, width=60, justify=CENTER)

#combobox
types=['Алфавит', 'Животные', 'Блоки', 'Декорации', 'Еда и напитки', 'Люди', 'Гуманоиды', 'Прочее', 'Монстры', 'Растения']

type = ttk.Combobox(typeframe, value=types, width=60)
type['state'] = 'readonly'

#Buttons
generateb = Button(text="Сгенерировать", command=generate)

#Image

img = ImageTk.PhotoImage(Image.open("gif.gif"))
labelimg = Label(image = img)

#####pack vse taki

partyidframe.pack()
partyid.pack()

slotframe.pack()
slot.pack()

nameframe.pack()
name.pack()

hdbidframe.pack()
hdbid.pack()

costframe.pack()
cost.pack()

typeframe.pack()
type.pack()

generateb.pack(padx=5, pady=5)

labelimg.pack(side=BOTTOM)

root.mainloop()
